name: axisofaction
favicon: null
layout_spectrum: 0.1488
typography_spectrum: 0.50039
title: Axis of Action
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#c9c9c9'
    - '#2a2a2a'
    - '#9c9c9c'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
